In [135]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

import pandas as pd
import re
import nltk

In [114]:
data = pd.read_csv("Tweets.csv")

In [115]:
data = data[data['airline_sentiment'] != 'neutral']

In [117]:
data2 = data[["airline_sentiment", "airline", "text"]]

In [118]:
airnames = data2["airline"].unique()
airnames = pd.Series(airnames)
airnames = airnames.str.lower()

airnames2 = airnames.str.replace(" ", "")
airnames = airnames.append(airnames2)
others = pd.Series(['americanair', '@'])
airnames = others.append(airnames)
airnames

0       americanair
1                 @
0    virgin america
1            united
2         southwest
3             delta
4        us airways
5          american
0     virginamerica
1            united
2         southwest
3             delta
4         usairways
5          american
dtype: object

In [119]:
proc_text = data2['text'].str.lower()

for i in airnames:
    proc_text = proc_text.str.replace(i, '')

In [120]:
data3 = pd.concat([proc_text, data["airline"], data["airline_sentiment"]], axis=1)

In [121]:
data3.head()

text         airline  \
1   plus you've added commercials to the experien...  Virgin America   
3   it's really aggressive to blast obnoxious "en...  Virgin America   
4           and it's a really big bad thing about it  Virgin America   
5   seriously would pay $30 a flight for seats th...  Virgin America   
6   yes, nearly every time i fly vx this “ear wor...  Virgin America   

  airline_sentiment  
1          positive  
3          negative  
4          negative  
5          negative  
6          positive

In [127]:
vectorizer = CountVectorizer(
    analyzer = 'word',
    lowercase = 1,
    max_features = 1000
)

features = vectorizer.fit_transform(
    proc_text
)

features_nd = features.toarray()

In [162]:
#print(vectorizer.get_feature_names())
#features_nd.shape
features_nd

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [149]:
dataVA = data3[data3['airline'] == 'Virgin America']
dataU = data3[data3['airline'] == 'United']
dataSW = data3[data3['airline'] == 'Southwest']
dataD = data3[data3['airline'] == 'Delta']
dataUSA = data3[data3['airline'] == 'US Airways']
dataA = data3[data3['airline'] == 'American']

In [150]:
train_dataVA = dataVA[:int(len(dataVA)*.8)]
train_dataU = dataU[:int(len(dataU)*.8)]
train_dataSW = dataSW[:int(len(dataSW)*.8)]
train_dataD = dataD[:int(len(dataD)*.8)]
train_dataUSA = dataUSA[:int(len(dataUSA)*.8)]
train_dataA = dataA[:int(len(dataA)*.8)]

train_data = pd.concat([train_dataVA,
                      train_dataU,
                      train_dataSW,
                      train_dataD,
                      train_dataUSA,
                      train_dataA], axis = 0)
train_data

text         airline  \
1       plus you've added commercials to the experien...  Virgin America   
3       it's really aggressive to blast obnoxious "en...  Virgin America   
4               and it's a really big bad thing about it  Virgin America   
5       seriously would pay $30 a flight for seats th...  Virgin America   
6       yes, nearly every time i fly vx this “ear wor...  Virgin America   
8                       well, i didn't…but now i do! :-d  Virgin America   
9       it was amazing, and arrived an hour early. yo...  Virgin America   
11      i &lt;3 pretty graphics. so much better than ...  Virgin America   
12      this is such a great deal! already thinking a...  Virgin America   
13      virginmedia i'm flying your #fabulous #seduct...  Virgin America   
14                                               thanks!  Virgin America   
15                        sfo-pdx schedule is still mia.  Virgin America   
16      so excited for my first cross country flight ...  Virgin America   
17       i flew from nyc to sfo last week and couldn'...  Virgin America   
18                                     i ❤️ flying . ☺️👍  Virgin America   
19      you know what would be amazingly awesome? bos...  Virgin America   
20      why are your first fares in may over three ti...  Virgin America   
21           i love this graphic. http://t.co/ut5grrwaaa  Virgin America   
22      i love the hipster innovation. you are a feel...  Virgin America   
24      you guys messed up my seating.. i reserved se...  Virgin America   
25      status match program.  i applied and it's bee...  Virgin America   
26      what happened 2 ur vegan food options?! at le...  Virgin America   
28      amazing to me that we can't get any cold air ...  Virgin America   
30      hi! i just bked a cool birthday trip with you...  Virgin America   
32      help, left expensive headphones on flight 89 ...  Virgin America   
33      awaiting my return phone call, just would pre...  Virgin America   
34      this is great news!  america could start flig...  Virgin America   
36      moodlighting is the only way to fly! best exp...  Virgin America   
37      freddieawards done and done! best airline aro...  Virgin America   
39      your chat support is not working on your site...  Virgin America   
...                                                  ...             ...   
14081   jameswester see, james, we only have 7 dedica...        American   
14083   , sitting on plane for 2.5hrs at gate due to ...        American   
14084   cjdjpdx not a valid response in 2015 for a mu...        American   
14086   kaps12 this is an international airline that ...        American   
14087                      great seats on this aircraft!        American   
14088  is rudeness and poor customers service a job r...        American   
14090   aa919 flight attendant freaks out and leaves ...        American   
14092   a worker just checked for ice on our plane us...        American   
14094   the wine served in  flights are watered down ...        American   
14096   we have 3 more passengers with me   there are...        American   
14097   patrichruben no, profit maximization is your ...        American   
14100   manuel_c "here for you" as in, yeah, we'll tw...        American   
14101   #flight293 was supposed to depart at 745 and ...        American   
14102   you have the worst customer service of any ai...        American   
14103   ezemanalyst why don't you tweet canned, imper...        American   
14104                         done!! thank you so much!!        American   
14105   nice aa employee making skillful excuses abou...        American   
14106   then taxi across dfw airport for 20 min to th...        American   
14107   24 hrs &amp; 2 cncld flights late flightr i'v...        American   
14108   delivered mom's delayed bag to the wrong plac...        American   
14109   yeah, try harder. no catering truck in sight....        American   
14110                   

In [151]:
test_dataVA = dataVA[int(len(dataVA)*.8):]
test_dataU = dataU[int(len(dataU)*.8):]
test_dataSW = dataSW[int(len(dataSW)*.8):]
test_dataD = dataD[int(len(dataD)*.8):]
test_dataUSA = dataUSA[int(len(dataUSA)*.8):]
test_dataA = dataA[int(len(dataA)*.8):]

test_data = pd.concat([test_dataVA,
                      test_dataU,
                      test_dataSW,
                      test_dataD,
                      test_dataUSA,
                      test_dataA], axis = 0)
test_data

text         airline  \
397     good to be home #texas #moodlighting http://t...  Virgin America   
398     i cannot even open my laptop in seat 4c and i...  Virgin America   
399     i am in seat 4c and i cannot even open my lap...  Virgin America   
401     thanks for that. been needing a way to make t...  Virgin America   
404     this is too cool!  never been on ur planes bu...  Virgin America   
406                                great. well deserved.  Virgin America   
407     fyi the info.com email address you say to con...  Virgin America   
408     status match - 2 weeks have gone by and no ne...  Virgin America   
409     your website sucks donkey dicks. just thought...  Virgin America   
411     all crap channels which is why i pay to watch...  Virgin America   
412                            got it. all set - thanks!  Virgin America   
415                 giants and . a match made in heaven.  Virgin America   
416     thank goodness!! also, see you friday, nwk&gt...  Virgin America   
417     how come you don't have an iphone app? still ...  Virgin America   
418     your back of seat entertainment system does n...  Virgin America   
419     when will vx use all 6 lga slots instead of 4...  Virgin America   
421     i luv ur people and product! 1 thing is y do ...  Virgin America   
422     thank you! see y'all soon! i'm excited to see...  Virgin America   
425     sad to learn you no longer fly sfo &gt; phl. ...  Virgin America   
427     has the most incredible customer service i've...  Virgin America   
429     , am i dreaming? did you really just open up ...  Virgin America   
430                                          omg finally  Virgin America   
433     kinda sucked my earphone jack didn't work on ...  Virgin America   
434     very poor experience. first computer problem ...  Virgin America   
436         #thankyou the dal-aus route makes my day!!!!  Virgin America   
437     awesome deals dal-aus for only $39 each way! ...  Virgin America   
439     love it, taking air on in their backyard! con...  Virgin America   
440     ​ is flying from love to austin now. that is ...  Virgin America   
443                    congrats vx on the new route! ✈️🎉  Virgin America   
444     i tried that. you offered to charge me an add...  Virgin America   
...                                                  ...             ...   
14605   trying to book a flight on hold- can't get th...        American   
14606   cancelled flights flights arbitrarily on same...        American   
14608   my flight was cancelled flightled from laguar...        American   
14609   &amp; if that wasn't enough, your staff have ...        American   
14610   i understand the weather issue but you can't ...        American   
14612   a friend is having flight cancelled flightlat...        American   
14613   i used the "call back" feature with an operat...        American   
14614   i need to be at work tomorrow at 8am, therefo...        American   
14615    ugh dump us in dfw w/no luggage then cancell...        American   
14616   cancelled flights my flight, doesn't send an ...        American   
14617                         dming you now! big thanks.        American   
14618   3078 is overweight so you pull 2 dozen passen...        American   
14619   i love your company and your staff is amazing...        American   
14620   i wait 2+ hrs for cs to call me back re why  ...        American   
14621   i've been on hold for 55 mins about my cancel...        American   
14622  i just need a place to sleep when i land witho...        American   
14623   love the new planes for the jfk-lax run.  may...        American   
14624   call me chairman, or call me emerald. after w...        American   
14625   flight 236 was great. fantastic cabin crew. a...        American   
14626   flight 953 nyc-buenos aires has been delay si...        American   
14627   flight cancelled flightled, can't go home unt...        American   
14628  thank you. “: jlh

In [152]:
features_VA = features_nd[:len(dataVA)]
features_U = features_nd[len(dataVA): len(dataVA)+len(dataU)]
features_SW = features_nd[len(dataVA)+len(dataU): len(dataVA)+len(dataU)+len(dataSW)]
features_D = features_nd[len(dataVA)+len(dataU)+len(dataSW): len(dataVA)+len(dataU)+len(dataSW)+len(dataD)]
features_USA = features_nd[len(dataVA)+len(dataU)+len(dataSW)+len(dataD): len(dataVA)+len(dataU)+len(dataSW)+len(dataD)+len(dataUSA)]
features_A = features_nd[len(dataVA)+len(dataU)+len(dataSW)+len(dataD)+len(dataUSA): len(dataVA)+len(dataU)+len(dataSW)+len(dataD)+len(dataUSA)+len(dataA)]

In [153]:
train_featuresVA = pd.DataFrame(features_VA[:int(len(features_VA)*.8)])
train_featuresU = pd.DataFrame(features_U[:int(len(features_U)*.8)])
train_featuresSW = pd.DataFrame(features_SW[:int(len(features_SW)*.8)])
train_featuresD = pd.DataFrame(features_D[:int(len(features_D)*.8)])
train_featuresUSA = pd.DataFrame(features_USA[:int(len(features_USA)*.8)])
train_featuresA = pd.DataFrame(features_A[:int(len(features_A)*.8)])

train_features = pd.concat([train_featuresVA,
                      train_featuresU,
                      train_featuresSW,
                      train_featuresD,
                      train_featuresUSA,
                      train_featuresA], axis = 0)
train_features = train_features.to_numpy()
train_features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [154]:
test_featuresVA = pd.DataFrame(features_VA[int(len(features_VA)*.8):])
test_featuresU = pd.DataFrame(features_U[int(len(features_U)*.8):])
test_featuresSW = pd.DataFrame(features_SW[int(len(features_SW)*.8):])
test_featuresD = pd.DataFrame(features_D[int(len(features_D)*.8):])
test_featuresUSA = pd.DataFrame(features_USA[int(len(features_USA)*.8):])
test_featuresA = pd.DataFrame(features_A[int(len(features_A)*.8):])

test_features = pd.concat([test_featuresVA,
                      test_featuresU,
                      test_featuresSW,
                      test_featuresD,
                      test_featuresUSA,
                      test_featuresA], axis = 0)
test_features = test_features.to_numpy()
test_features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [156]:
log_model = LogisticRegression()
log_model = log_model.fit(X=train_features, y=train_data['airline_sentiment'])
y_pred = log_model.predict(test_features)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [159]:
from sklearn.metrics import accuracy_score

y_test = test_data['airline_sentiment']
print(accuracy_score(y_test, y_pred))

0.8641280830809174
